import{i as c,S as B}from"./assets/vendor-CZCnFrqK.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(o){if(o.ep)return;o.ep=!0;const r=i(o);fetch(o.href,r)}})();let h=1;const y=async(e,t=1,i=20)=>{const a=e?15:i,o="47502659-8e710eb0ff3e952458316b5b2",r="https://pixabay.com/api/";m(!0);try{const n=`${r}?key=${o}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${a}`;console.log("Запрос к API:",n);const l=await fetch(n);if(!l.ok)throw new Error(`Ошибка при получении данных: ${l.statusText}`);const s=await l.json();if(console.log("Полученные данные:",s),!s.hits||s.hits.length===0)throw new Error("No images found");return(s.hits.length<a||s.totalHits<=t*a)&&M(),s.hits}catch(n){return console.error(n),[]}finally{m(!1)}},m=e=>{const t=document.getElementById("loader");t?t.style.display=e?"block":"none":console.error('Элемент с id "loader" не найден')},M=()=>{const e=document.getElementById("loadMoreButton");e?(e.classList.add("is-hidden"),console.log("Кнопка скрыта:",e)):console.error('Элемент с id "loadMoreButton" не найден')},g=document.getElementById("loadMoreButton");g?g.addEventListener("click",async()=>{g.classList.add("is-hidden"),m(!0);const e="nature";h++;const t=await y(e,h,15);t.length>0&&P(t),m(!1)}):console.error('Кнопка "Load More" не найдена');const P=e=>{const t=document.getElementById("imageContainer");t?e.forEach(i=>{const a=document.createElement("img");a.src=i.webformatURL,a.alt=i.tags||"Image",t.appendChild(a)}):console.error('Элемент с id "imageContainer" не найден')},L=e=>{const t=document.querySelector(".gallery");if(console.log("Изображения для отображения:",e),e.length===0){t.children.length===0&&(t.innerHTML="<p>No images found</p>");return}const i=e.map(({webformatURL:r,largeImageURL:n,tags:l,likes:s,views:v,comments:I,downloads:S})=>`
      <div class="card">
        <a href="${n}" target="_blank">
          <img 
            src="${r}" 
            data-src="${n}" 
            alt="${l||"Image"}" 
            loading="lazy"
            class="lazy-load" 
          />
        </a>
        <p>Likes: ${s} | Views: ${v} | Comments: ${I} | Downloads: ${S}</p>
      </div>
    `).join("");t.insertAdjacentHTML("beforeend",i);const a=document.querySelectorAll(".lazy-load"),o=new IntersectionObserver((r,n)=>{r.forEach(l=>{if(l.isIntersecting){const s=l.target;s.src=s.getAttribute("data-src"),s.classList.remove("lazy-load"),n.unobserve(s)}})},{rootMargin:"0px 0px 50px 0px"});a.forEach(r=>{o.observe(r)})},p=document.querySelector("#search-form"),q=document.querySelector("#search-input"),b=document.querySelector(".gallery");document.querySelector(".load-more");const u=document.getElementById("loadMoreButton");let f=1,d="nature";p?p.addEventListener("submit",async e=>{if(e.preventDefault(),d=q.value.trim(),!d){c.error({message:"Please enter a search term"});return}f=1,w(),x();try{const t=await y(d,f);t.length===0?c.info({message:"Sorry, there are no images matching your search query. Please try again!"}):(L(t),$())}catch{c.error({message:"Something went wrong, please try again!"})}finally{E()}}):console.error("Search form element not found");u?u.addEventListener("click",async()=>{if(!d){c.error({message:"Please enter a search term"});return}u.style.display="none",w();try{f++;const e=await y(d,f);e.length===0?(c.info({message:"Sorry, there are no more images to load."}),hideLoadMoreButton()):(L(e),$())}catch{c.error({message:"Something went wrong, please try again!"})}finally{E(),u.style.display="block"}}):console.error("Load more button element not found");function w(){const e=document.createElement("div");e.classList.add("loader"),e.textContent="Loading...",b.appendChild(e)}function E(){const e=document.querySelector(".loader");e&&e.remove()}function x(){b.innerHTML=""}function $(){new B(".gallery a")}
//# sourceMappingURL=index.js.map
