import{i as l,S as I}from"./assets/vendor-CZCnFrqK.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(o){if(o.ep)return;o.ep=!0;const r=i(o);fetch(o.href,r)}})();let g=1;const f=async(e,t=1,i=20)=>{const s=e?15:i,o="47502659-8e710eb0ff3e952458316b5b2",r="https://pixabay.com/api/";y(!0);try{const n=`${r}?key=${o}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${s}`;console.log("Запрос к API:",n);const c=await fetch(n);if(!c.ok)throw new Error(`Ошибка при получении данных: ${c.statusText}`);const a=await c.json();if(console.log("Полученные данные:",a),!a.hits||a.hits.length===0)throw new Error("No images found");return(a.hits.length<s||a.totalHits<=t*s)&&B(),a.hits}catch(n){return console.error(n),[]}finally{y(!1)}},y=e=>{const t=document.getElementById("loader");t&&(e?t.style.display="block":t.style.display="none")},B=()=>{const e=document.getElementById("loadMoreButton");e.classList.add("is-hidden"),console.log("Кнопка скрыта:",e)};document.getElementById("loadMoreButton").addEventListener("click",async()=>{document.getElementById("loadMoreButton"),document.querySelector(".loader");const e="nature";g++;const t=await f(e,g,15);t.length>0&&M(t)});const M=e=>{const t=document.getElementById("imageContainer");t&&e.forEach(i=>{const s=document.createElement("img");s.src=i.webformatURL,t.appendChild(s)})},p=e=>{const t=document.querySelector(".gallery");if(console.log("Изображения для отображения:",e),e.length===0){t.children.length===0&&(t.innerHTML="<p>No images found</p>");return}const i=e.map(({webformatURL:r,largeImageURL:n,tags:c,likes:a,views:v,comments:S,downloads:$})=>`
      <div class="card">
        <a href="${n}" target="_blank">
          <img 
            src="${r}" 
            data-src="${n}" 
            alt="${c||"Image"}" 
            loading="lazy"
            class="lazy-load" 
          />
        </a>
        <p>Likes: ${a} | Views: ${v} | Comments: ${S} | Downloads: ${$}</p>
      </div>
    `).join("");t.insertAdjacentHTML("beforeend",i);const s=document.querySelectorAll(".lazy-load"),o=new IntersectionObserver((r,n)=>{r.forEach(c=>{if(c.isIntersecting){const a=c.target;a.src=a.getAttribute("data-src"),a.classList.remove("lazy-load"),n.unobserve(a)}})},{rootMargin:"0px 0px 50px 0px"});s.forEach(r=>{o.observe(r)})},h=document.querySelector("#search-form"),P=document.querySelector("#search-input"),L=document.querySelector(".gallery");document.querySelector(".load-more");const u=document.getElementById("loadMoreButton");let m=1,d="nature";h?h.addEventListener("submit",async e=>{if(e.preventDefault(),d=P.value.trim(),!d){l.error({message:"Please enter a search term"});return}m=1,b(),q();try{const t=await f(d,m);t.length===0?l.info({message:"Sorry, there are no images matching your search query. Please try again!"}):(p(t),E())}catch{l.error({message:"Something went wrong, please try again!"})}finally{w()}}):console.error("Search form element not found");u?u.addEventListener("click",async()=>{if(!d){l.error({message:"Please enter a search term"});return}u.style.display="none",b();try{m++;const e=await f(d,m);e.length===0?(l.info({message:"Sorry, there are no more images to load."}),hideLoadMoreButton()):(p(e),E())}catch{l.error({message:"Something went wrong, please try again!"})}finally{w(),u.style.display="block"}}):console.error("Load more button element not found");function b(){const e=document.createElement("div");e.classList.add("loader"),e.textContent="Loading...",L.appendChild(e)}function w(){const e=document.querySelector(".loader");e&&e.remove()}function q(){L.innerHTML=""}function E(){new I(".gallery a")}
//# sourceMappingURL=index.js.map
